---

name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Run unit tests
        run: npm run test
      - name: Run cypress
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm run local-dev
