---

name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Use nodejs 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: yarn install
      - name: Run unit tests
        run: npm run test
      - name: Run cypress
        uses: cypress-io/github-action@v5
        with:
          build: npm run build-ci
          start: npm run local-dev
